from __future__ import annotations

import os
from pathlib import Path

from pydantic import BaseModel, Field

from app.core.runtime import is_cloud


APP_VERSION = "2.1.1"


class Settings(BaseModel):
    app_name: str = Field(default_factory=lambda: os.getenv("NEXUSTI_APP_NAME", "Agente Fino"))
    app_version: str = APP_VERSION
    runtime: str = Field(default_factory=lambda: os.getenv("AGENTE_FINO_RUNTIME", "cloud").strip().lower())
    database_url: str = Field(default_factory=lambda: os.getenv("DATABASE_URL", ""))
    db_engine: str = Field(default_factory=lambda: os.getenv("AGENTE_FINO_DB_ENGINE", "postgres" if os.getenv("DATABASE_URL") else ("memory" if is_cloud() else "sqlite")).strip().lower())
    admin_user: str = Field(default_factory=lambda: os.getenv("AGENTE_FINO_ADMIN_USER", "Pedro"))
    admin_email: str = Field(default_factory=lambda: os.getenv("AGENTE_FINO_ADMIN_EMAIL", ""))
    admin_password_hash: str = Field(default_factory=lambda: os.getenv("AGENTE_FINO_ADMIN_PASSWORD_HASH", ""))
    rag_enabled: bool = Field(default_factory=lambda: os.getenv("AGENTE_FINO_RAG_ENABLED", "false" if is_cloud() else "true").lower() == "true")
    memory_enabled: bool = Field(default_factory=lambda: os.getenv("AGENTE_FINO_MEMORY_ENABLED", "true").lower() == "true")
    host: str = Field(default_factory=lambda: os.getenv("NEXUSTI_HOST", "127.0.0.1"))
    port: int = Field(default_factory=lambda: int(os.getenv("NEXUSTI_PORT", "8765")))
    db_path: Path = Field(default_factory=lambda: Path(os.getenv("NEXUSTI_DB_PATH", "data/nexusti.db")))
    vector_store_provider: str = Field(default_factory=lambda: os.getenv("NEXUSTI_VECTOR_STORE_PROVIDER", "sqlite-fts5"))
    vector_store_url: str = Field(default_factory=lambda: os.getenv("NEXUSTI_VECTOR_STORE_URL", ""))
    embedding_provider: str = Field(default_factory=lambda: os.getenv("NEXUSTI_EMBEDDING_PROVIDER", "local-placeholder"))
    embedding_model: str = Field(default_factory=lambda: os.getenv("NEXUSTI_EMBEDDING_MODEL", ""))
    temp_file_min_age_seconds: int = 600
    process_limit: int = 25
    cpu_measure_interval_seconds: float = 0.35
    process_measure_interval_seconds: float = 0.25
    web_enabled: bool = Field(default_factory=lambda: os.getenv("NEXUSTI_WEB_ENABLED", "true").lower() == "true")
    web_require_citations: bool = Field(default_factory=lambda: os.getenv("NEXUSTI_WEB_REQUIRE_CITATIONS", "true").lower() == "true")
    web_require_source_ranking: bool = Field(default_factory=lambda: os.getenv("NEXUSTI_WEB_REQUIRE_SOURCE_RANKING", "true").lower() == "true")
    web_max_results: int = Field(default_factory=lambda: int(os.getenv("NEXUSTI_WEB_MAX_RESULTS", "8")))
    web_max_pages_fetch: int = Field(default_factory=lambda: int(os.getenv("NEXUSTI_WEB_MAX_PAGES_FETCH", "5")))
    web_timeout: int = Field(default_factory=lambda: int(os.getenv("NEXUSTI_WEB_TIMEOUT", "15")))
    web_cache_enabled: bool = Field(default_factory=lambda: os.getenv("NEXUSTI_WEB_CACHE_ENABLED", "true").lower() == "true")
    web_cache_ttl_minutes: int = Field(default_factory=lambda: int(os.getenv("NEXUSTI_WEB_CACHE_TTL_MINUTES", "120")))
    web_provider: str = Field(default_factory=lambda: os.getenv("NEXUSTI_WEB_PROVIDER", "duckduckgo_html"))
    searxng_url: str = Field(default_factory=lambda: os.getenv("NEXUSTI_SEARXNG_URL", ""))
    web_user_agent: str = Field(default_factory=lambda: os.getenv("NEXUSTI_WEB_USER_AGENT", "AgenteFino-ResearchBot/1.0"))
    web_safe_domains_only: bool = Field(default_factory=lambda: os.getenv("NEXUSTI_WEB_SAFE_DOMAINS_ONLY", "false").lower() == "true")
    model_provider: str = Field(default_factory=lambda: os.getenv("DEFAULT_PROVIDER", os.getenv("NEXUSTI_MODEL_PROVIDER", "gemini")))
    gemini_api_key: str = Field(default_factory=lambda: os.getenv("GEMINI_API_KEY", ""))
    gemini_model: str = Field(default_factory=lambda: os.getenv("GEMINI_MODEL", "gemini-2.5-flash"))
    gemini_base_url: str = Field(default_factory=lambda: os.getenv("GEMINI_BASE_URL", "https://generativelanguage.googleapis.com/v1beta"))
    gemini_timeout_seconds: float = Field(default_factory=lambda: float(os.getenv("GEMINI_TIMEOUT_SECONDS", "35")))
    gemini_status_cache_seconds: float = Field(default_factory=lambda: float(os.getenv("GEMINI_STATUS_CACHE_SECONDS", "60")))
    ollama_enabled: bool = Field(default_factory=lambda: False if is_cloud() else os.getenv("NEXUSTI_OLLAMA_ENABLED", "true").lower() == "true")
    ollama_url: str = Field(default_factory=lambda: os.getenv("OLLAMA_BASE_URL", os.getenv("NEXUSTI_OLLAMA_URL", "http://localhost:11434")))
    ollama_model: str = Field(default_factory=lambda: os.getenv("OLLAMA_MODEL", os.getenv("NEXUSTI_OLLAMA_MODEL", "qwen2.5:3b")))
    ollama_fallback_model: str = Field(default_factory=lambda: os.getenv("NEXUSTI_OLLAMA_FALLBACK_MODEL", "llama3.1:8b"))
    ollama_health_timeout_seconds: float = Field(default_factory=lambda: float(os.getenv("NEXUSTI_OLLAMA_HEALTH_TIMEOUT_SECONDS", "2.0")))
    ollama_chat_timeout_seconds: float = Field(default_factory=lambda: float(os.getenv("NEXUSTI_OLLAMA_CHAT_TIMEOUT_SECONDS", "90")))
    openai_enabled: bool = Field(default_factory=lambda: os.getenv("OPENAI_ENABLED", os.getenv("NEXUSTI_OPENAI_ENABLED", "false")).lower() == "true")
    openai_base_url: str = Field(default_factory=lambda: os.getenv("NEXUSTI_OPENAI_BASE_URL", "https://api.openai.com/v1"))
    openai_api_key: str = Field(default_factory=lambda: os.getenv("OPENAI_API_KEY", os.getenv("NEXUSTI_OPENAI_API_KEY", "")))
    openai_model: str = Field(default_factory=lambda: os.getenv("OPENAI_MODEL", os.getenv("NEXUSTI_OPENAI_MODEL", "gpt-5.4-mini")))
    openai_fallback_model: str = Field(default_factory=lambda: os.getenv("OPENAI_FALLBACK_MODEL", os.getenv("NEXUSTI_OPENAI_FALLBACK_MODEL", "gpt-5.4-mini")))
    openai_verifier_model: str = Field(default_factory=lambda: os.getenv("OPENAI_VERIFIER_MODEL", os.getenv("NEXUSTI_OPENAI_VERIFIER_MODEL", "")))
    openai_use_for_verification: bool = Field(default_factory=lambda: os.getenv("OPENAI_USE_FOR_VERIFICATION", "true").lower() == "true")
    openai_timeout_seconds: int = Field(default_factory=lambda: int(os.getenv("OPENAI_TIMEOUT_SECONDS", os.getenv("NEXUSTI_OPENAI_TIMEOUT_SECONDS", "12"))))
    openai_fast_enabled: bool = Field(default_factory=lambda: os.getenv("OPENAI_FAST_ENABLED", "true").lower() == "true")
    openai_web_search_enabled: bool = Field(default_factory=lambda: os.getenv("OPENAI_WEB_SEARCH_ENABLED", "false").lower() == "true")
    openai_compat_enabled: bool = Field(default_factory=lambda: os.getenv("NEXUSTI_OPENAI_COMPAT_ENABLED", "false").lower() == "true")
    openai_compat_base_url: str = Field(default_factory=lambda: os.getenv("NEXUSTI_OPENAI_COMPAT_BASE_URL", ""))
    openai_compat_api_key: str = Field(default_factory=lambda: os.getenv("NEXUSTI_OPENAI_COMPAT_API_KEY", ""))
    openai_compat_model: str = Field(default_factory=lambda: os.getenv("NEXUSTI_OPENAI_COMPAT_MODEL", ""))
    litellm_base_url: str = Field(default_factory=lambda: os.getenv("LITELLM_BASE_URL", ""))
    litellm_api_key: str = Field(default_factory=lambda: os.getenv("LITELLM_API_KEY", ""))
    litellm_model: str = Field(default_factory=lambda: os.getenv("LITELLM_MODEL", "gpt-4o-mini"))
    litellm_timeout_seconds: int = Field(default_factory=lambda: int(os.getenv("LITELLM_TIMEOUT_SECONDS", "30")))
    local_rules_enabled: bool = Field(default_factory=lambda: os.getenv("LOCAL_RULES_ONLY_FALLBACK", os.getenv("NEXUSTI_LOCAL_RULES_ENABLED", "true")).lower() == "true")
    langfuse_enabled: bool = Field(default_factory=lambda: os.getenv("NEXUSTI_LANGFUSE_ENABLED", "false").lower() == "true")
    langfuse_public_key: str = Field(default_factory=lambda: os.getenv("NEXUSTI_LANGFUSE_PUBLIC_KEY", ""))
    langfuse_secret_key: str = Field(default_factory=lambda: os.getenv("NEXUSTI_LANGFUSE_SECRET_KEY", ""))
    langfuse_host: str = Field(default_factory=lambda: os.getenv("NEXUSTI_LANGFUSE_HOST", ""))
    fusion_enabled: bool = Field(default_factory=lambda: os.getenv("NEXUS_FUSION_ENABLED", "true").lower() == "true")
    fusion_default_mode: str = Field(default_factory=lambda: os.getenv("NEXUS_DEFAULT_MODE", "balanced"))
    fusion_allow_multi_model: bool = Field(default_factory=lambda: os.getenv("NEXUS_ALLOW_MULTI_MODEL", "true").lower() == "true")
    fusion_allow_verifier: bool = Field(default_factory=lambda: os.getenv("NEXUS_ALLOW_VERIFIER", "true").lower() == "true")
    fusion_max_models_per_request: int = Field(default_factory=lambda: int(os.getenv("NEXUS_MAX_MODELS_PER_REQUEST", "2")))
    nexus_timeout_seconds: int = Field(default_factory=lambda: int(os.getenv("NEXUS_TIMEOUT_SECONDS", "30")))
    autonomy_enabled: bool = Field(default_factory=lambda: os.getenv("NEXUS_ENABLE_AUTONOMY", "true").lower() == "true")
    autonomy_level: int = Field(default_factory=lambda: int(os.getenv("NEXUS_AUTONOMY_LEVEL", "1")))
    require_confirmation_for_actions: bool = Field(default_factory=lambda: os.getenv("NEXUS_REQUIRE_CONFIRMATION_FOR_ACTIONS", "true").lower() == "true")
    enable_lens: bool = Field(default_factory=lambda: os.getenv("NEXUS_ENABLE_LENS", "true").lower() == "true")
    enable_deep_search: bool = Field(default_factory=lambda: os.getenv("NEXUS_ENABLE_DEEP_SEARCH", "true").lower() == "true")
    enable_missions: bool = Field(default_factory=lambda: os.getenv("NEXUS_ENABLE_MISSIONS", "true").lower() == "true")
    enable_artifacts: bool = Field(default_factory=lambda: os.getenv("NEXUS_ENABLE_ARTIFACTS", "true").lower() == "true")
    enable_training_export: bool = Field(default_factory=lambda: os.getenv("NEXUS_ENABLE_TRAINING_EXPORT", "true").lower() == "true")
    vector_store: str = Field(default_factory=lambda: os.getenv("VECTOR_STORE", "disabled" if is_cloud() else "sqlite"))
    chroma_path: str = Field(default_factory=lambda: os.getenv("CHROMA_PATH", "data/chroma"))
    qdrant_url: str = Field(default_factory=lambda: os.getenv("QDRANT_URL", ""))
    fast_provider_timeout_seconds: float = Field(default_factory=lambda: float(os.getenv("NEXUS_FAST_PROVIDER_TIMEOUT_SECONDS", "6")))
    fast_total_timeout_seconds: float = Field(default_factory=lambda: float(os.getenv("NEXUS_FAST_TOTAL_TIMEOUT_SECONDS", "4")))
    balanced_provider_timeout_seconds: float = Field(default_factory=lambda: float(os.getenv("NEXUS_BALANCED_PROVIDER_TIMEOUT_SECONDS", "15")))
    expert_provider_timeout_seconds: float = Field(default_factory=lambda: float(os.getenv("NEXUS_EXPERT_PROVIDER_TIMEOUT_SECONDS", "25")))
    ollama_fast_timeout_seconds: float = Field(default_factory=lambda: float(os.getenv("NEXUS_OLLAMA_FAST_TIMEOUT_SECONDS", "3.2")))
    fast_max_output_tokens: int = Field(default_factory=lambda: max(16, int(os.getenv("NEXUS_FAST_MAX_OUTPUT_TOKENS", "32"))))
    darkforest_enabled: bool = Field(default_factory=lambda: os.getenv("DARKFOREST_ENABLED", "true").lower() == "true")
    darkforest_path: str = Field(default_factory=lambda: os.getenv("DARKFOREST_PATH", "./tools/DarkForest-Hunter-OpenAI"))
    darkforest_max_runtime: int = Field(default_factory=lambda: max(3, int(os.getenv("DARKFOREST_MAX_RUNTIME", "120"))))
    darkforest_mask_secrets: bool = Field(default_factory=lambda: os.getenv("DARKFOREST_MASK_SECRETS", "true").lower() == "true")
    darkforest_save_history: bool = Field(default_factory=lambda: os.getenv("DARKFOREST_SAVE_HISTORY", "true").lower() == "true")
    mcp_brasil_enabled: bool = Field(default_factory=lambda: os.getenv("MCP_BRASIL_ENABLED", "true").lower() == "true")
    mcp_brasil_path: str = Field(default_factory=lambda: os.getenv("MCP_BRASIL_PATH", "./tools/mcp-brasil"))
    mcp_brasil_transport: str = Field(default_factory=lambda: os.getenv("MCP_BRASIL_TRANSPORT", "http"))
    mcp_brasil_host: str = Field(default_factory=lambda: os.getenv("MCP_BRASIL_HOST", "127.0.0.1"))
    mcp_brasil_port: int = Field(default_factory=lambda: int(os.getenv("MCP_BRASIL_PORT", "8766")))
    mcp_brasil_auth_mode: str = Field(default_factory=lambda: os.getenv("MCP_BRASIL_AUTH_MODE", "none"))
    mcp_brasil_auto_start: bool = Field(default_factory=lambda: os.getenv("MCP_BRASIL_AUTO_START", "true").lower() == "true")
    mcp_brasil_timeout: int = Field(default_factory=lambda: int(os.getenv("MCP_BRASIL_TIMEOUT", "60")))
    mcp_brasil_allowed_features: str = Field(default_factory=lambda: os.getenv("MCP_BRASIL_ALLOWED_FEATURES", ""))
    mcp_brasil_datasets: str = Field(default_factory=lambda: os.getenv("MCP_BRASIL_DATASETS", ""))
    public_data_enabled: bool = Field(default_factory=lambda: os.getenv("PUBLIC_DATA_ENABLED", "true").lower() == "true")
    public_data_timeout_seconds: float = Field(default_factory=lambda: float(os.getenv("PUBLIC_DATA_TIMEOUT_SECONDS", "15")))
    document_lookup_enabled: bool = Field(default_factory=lambda: os.getenv("DOCUMENT_LOOKUP_ENABLED", "false").lower() == "true")
    document_lookup_base_url: str = Field(default_factory=lambda: os.getenv("DOCUMENT_LOOKUP_BASE_URL", ""))
    document_lookup_api_key: str = Field(default_factory=lambda: os.getenv("DOCUMENT_LOOKUP_API_KEY", ""))
    document_lookup_timeout_seconds: float = Field(default_factory=lambda: float(os.getenv("DOCUMENT_LOOKUP_TIMEOUT_SECONDS", "15")))
    document_lookup_method: str = Field(default_factory=lambda: os.getenv("DOCUMENT_LOOKUP_METHOD", "GET"))
    document_lookup_cpf_path: str = Field(default_factory=lambda: os.getenv("DOCUMENT_LOOKUP_CPF_PATH", "/cpf/{document}"))
    document_lookup_cnpj_path: str = Field(default_factory=lambda: os.getenv("DOCUMENT_LOOKUP_CNPJ_PATH", "/cnpj/{document}"))
    document_lookup_api_key_header: str = Field(default_factory=lambda: os.getenv("DOCUMENT_LOOKUP_API_KEY_HEADER", "Authorization"))
    document_lookup_api_key_prefix: str = Field(default_factory=lambda: os.getenv("DOCUMENT_LOOKUP_API_KEY_PREFIX", "Bearer "))
    cpf_lookup_rate_limit_per_hour: int = Field(default_factory=lambda: max(1, int(os.getenv("CPF_LOOKUP_RATE_LIMIT_PER_HOUR", "100"))))
    cnpj_lookup_rate_limit_per_hour: int = Field(default_factory=lambda: max(1, int(os.getenv("CNPJ_LOOKUP_RATE_LIMIT_PER_HOUR", "300"))))
    sherlock_enabled: bool = Field(default_factory=lambda: os.getenv("SHERLOCK_ENABLED", "true").lower() == "true")
    sherlock_cpf_lab_enabled: bool = Field(default_factory=lambda: os.getenv("SHERLOCK_CPF_LAB_ENABLED", "true").lower() == "true")
    cnpj_lookup_enabled: bool = Field(default_factory=lambda: os.getenv("CNPJ_LOOKUP_ENABLED", "true").lower() == "true")
    cnpj_lookup_provider: str = Field(default_factory=lambda: os.getenv("CNPJ_LOOKUP_PROVIDER", "brasilapi").strip().lower())
    cnpj_lookup_timeout_seconds: float = Field(default_factory=lambda: float(os.getenv("CNPJ_LOOKUP_TIMEOUT_SECONDS", "10")))
    cnpj_cache_ttl_seconds: int = Field(default_factory=lambda: max(60, int(os.getenv("CNPJ_CACHE_TTL_SECONDS", "21600"))))
    redis_url: str = Field(default_factory=lambda: os.getenv("REDIS_URL", ""))
    consulta_cache_enabled: bool = Field(default_factory=lambda: os.getenv("CONSULTA_CACHE_ENABLED", "true").lower() == "true")


settings = Settings()
